# Generated by Django 2.1.5 on 2020-02-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0029_auto_20200207_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
