# Generated by Django 2.1.5 on 2020-02-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0030_project_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='Project_Image'),
        ),
    ]
