# Generated by Django 2.1.5 on 2020-02-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0032_auto_20200213_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='photo_sanad',
            field=models.ImageField(default='default.png', upload_to='sanad_Image'),
        ),
    ]
