# Generated by Django 2.1.5 on 2020-02-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0033_auto_20200213_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='photo',
            field=models.ImageField(blank=True, upload_to='L:\\18Bahman\\10ufl\\media'),
        ),
    ]
