# Generated by Django 2.1.5 on 2020-02-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0034_auto_20200214_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='photo',
            field=models.ImageField(blank=True, upload_to='charity_Image'),
        ),
    ]
