# Generated by Django 2.1.5 on 2020-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0035_auto_20200214_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='photo',
            field=models.ImageField(blank=True, upload_to='charity_Image/'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='photo_sanad',
            field=models.ImageField(default='default.png', upload_to='sanad_Image/'),
        ),
    ]
