# Generated by Django 2.1.5 on 2020-01-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charityes2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_tasisi', models.CharField(max_length=10)),
                ('web', models.CharField(max_length=30)),
                ('phone_markaz', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('sabt_number', models.CharField(max_length=30)),
                ('explain', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
