# Generated by Django 2.1.5 on 2020-01-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityes', '0002_charityes2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charityes',
        ),
    ]
