# Generated by Django 2.1.5 on 2020-01-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityes', '0003_delete_charityes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=15)),
                ('codemeli', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
